# Stage 1: Build the app
FROM node:18-alpine AS build

WORKDIR /app

COPY package*.json ./

RUN rm -rf node_modules

RUN npm install

RUN npm install -g http-serve

COPY . .

RUN npm run build-storybook

EXPOSE 6006

CMD ["http-serve", "storybook-static", "-p", "6006", "-a", "0.0.0.0"]

