version: "3.8"

services:
  sb-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "6006:6006"
    environment:
      - HOST=0.0.0.0
      - PORT=6006
      - ENVIRONMENT=localhost
    command: npm run storybook:prod
    networks:
      - storybook_network
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
networks:
  storybook_network:
    driver: bridge
