version: "3.8"

services:
  sb-app-prod:
    container_name: sb-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "6006:6006"
    environment:
      - HOST=0.0.0.0
      - PORT=6006
      - ENVIRONMENT=localhost
    # command: npx serve -s /app/storybook-static
    networks:
      - sb_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6006"]
      interval: 10s
      retries: 5
      timeout: 5s
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  backstopjs:
    # image: backstopjs/backstopjs:latest
    build:
      context: .
      dockerfile: Dockerfile.backstop
    volumes:
      - ./backstop_data:/backstop_data
      - .:/app
    entrypoint: [
        # "/usr/local/bin/wait-for-it.sh",
        # "sb-app-prod:6006",
        # "--",
        "backstop",
        # "${COMMAND:-test}",
        # "--configPath=/app/backstop.config.cjs",
      ]
    # the below syntax sets the default value to test if COMMAND=approve is not provided while running docker compose up command like so COMMAND=approve docker compose up
    command:
      ["${COMMAND:-test}", "--configPath=/app/backstop.config.cjs", "--no-open"]
    depends_on:
      - sb-app-prod
    networks:
      - sb_network
    environment:
      - CI=true
      - ENVIRONMENT=docker
    # restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

networks:
  sb_network:
    driver: bridge
