version: "3.8"

services:
  sb-app-prod:
    container_name: sb-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "6006:6006"
    environment:
      - HOST=0.0.0.0
      - CI=true
      - PORT=6006
      - ENVIRONMENT=localhost
    networks:
      - sb_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6006"]
      interval: 10s
      retries: 5
      timeout: 5s
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  backstopjs:
    build:
      context: .
      dockerfile: Dockerfile.backstop
    volumes:
      - backstop_data:/app/backstop_data # named volume here
    entrypoint:
      [
        "/usr/local/bin/wait-for-it.sh",
        "sb-app-prod:6006",
        "--",
        "backstop",
        "${COMMAND:-test}",
        "--configPath=/app/backstop.config.cjs",
        "--no-open",
      ]
    depends_on:
      - sb-app-prod
    networks:
      - sb_network
    environment:
      - CI=true
      - ENVIRONMENT=docker
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

volumes:
  backstop_data: # explicitly define volumes to prevent duplication
    driver: local

networks:
  sb_network:
    driver: bridge
