name: Approve Visual Changes

on:
  issue_comment:
    types: [created]

jobs:
  stop-containers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Stop all running containers
        run: |
          docker compose -f docker-compose.prod.yml down

  approve-backstop:
    needs: stop-containers
    runs-on: ubuntu-latest
    if: |
      github.event.comment.body == '@bot approve visual changes'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run approval containers
        run: |
          COMMAND=approve docker compose -f docker-compose.prod.yml up
          echo "Changes Approved!"

      - name: Commit and push updated reference images
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add backstop_data/bitmaps_reference
          git commit -m "Approve BackstopJS visual changes"
          git push
