name: Visual Regression Testing

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    branches:
      - master
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: "docker:19.03"
        options: --privileged

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm install

      - name: Build Application with Vite
        run: npm run build

      - name: Build Storybook
        run: npm run build-storybook

      - name: Build and Run Docker Container
        run: |
          docker buildx build --platform linux/amd64 -t vite-sb -f Dockerfile.prod --no-cache . 
          docker compose -f docker-compose.prod.yml up 
          docker compose -f docker-compose.prod.yml down || true
        continue-on-error: true

      - name: Upload Backstop Results (if failed)
        uses: actions/upload-artifact@v3
        with:
          name: backstop-results
          path: backstop_data/html_report

      - name: Comment with BackstopJS Results
        uses: actions/github-script@v6
        with:
          script: |
            const runId = process.env.GITHUB_RUN_ID;
            const repo = `${{ github.repository }}`;
            const commentBody = `
              ## :warning: Visual regression test failed
              Please [view the BackstopJS report](https://github.com/${repo}/actions/runs/${runId}) and approve changes if necessary.
            `;
            github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody,
            });
  approve:
    runs-on: ubuntu-latest
    needs: build
    if: failure()

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: Approve BackstopJS changes
        run: npm run backstop:approve
