name: BackstopJS Approval

on:
  workflow_dispatch:

jobs:
  approve-backstopjs:
    runs-on: ubuntu-latest
    services:
      docker:
        image: "docker:19.03"
        options: --privileged
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm install

      - name: Build Storybook
        run: npm run build-storybook

      # Run test before the approval
      - name: Build and Run Docker Container
        run: |
          docker buildx build --platform linux/amd64 -t vite-sb -f Dockerfile.prod .
          docker compose -f docker-compose.prod.yml up --exit-code-from backstopjs

      # Build Docker and run BackstopJS
      - name: Build and Run Docker Container
        run: |
          docker buildx build --platform linux/amd64 -t vite-sb -f Dockerfile.prod .
          COMMAND=approve docker compose -f docker-compose.prod.yml up --exit-code-from backstopjs

      - name: Commit and Push Approved Reference Images
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add backstop_data/bitmaps_reference
          git commit -m "Approve BackstopJS visual changes"
          git push origin ${{ github.event.pull_request.head.ref }} --force
