name: Visual Regression Testing

permissions:
  contents: write
  pull-requests: write

on:
  pull_request:
    branches:
      - master
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: "docker:19.03"
        options: --privileged

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm install

      - name: Build Application with Vite
        run: npm run build

      - name: Build Storybook
        run: npm run build-storybook

      # Build Docker and run BackstopJS
      - name: Build and Run Docker Container
        run: |
          docker buildx build --platform linux/amd64 -t vite-sb -f Dockerfile.prod .
          docker compose -f docker-compose.prod.yml up --exit-code-from backstopjs

      - name: Upload Backstop Results
        uses: actions/upload-artifact@v3
        with:
          name: backstop-results
          path: |
            backstop_data/html_report/
            backstop_data/bitmaps_reference/
            backstop_data/bitmaps_test/

      # - name: Comment with BackstopJS Results
      #   uses: actions/github-script@v6
      #   with:
      #     script: |
      #       const runId = process.env.GITHUB_RUN_ID;
      #       const repo = `${{ github.repository }}`;
      #       const commentBody = `
      #         ## :warning: Visual regression report
      #         Please [view the BackstopJS report](https://github.com/${repo}/actions/runs/${runId}) and approve changes if necessary.
      #       `;
      #       github.rest.issues.createComment({
      #         issue_number: context.payload.pull_request.number,
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         body: commentBody,
      #       });
      - name: Deploy BackstopJS Report to GitHub Pages
        if: failure()
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git fetch origin gh-pages
          git checkout --orphan gh-pages
          cp -r backstop_data/html_report/ ./html_report  
          cp -r backstop_data/bitmaps_reference ./bitmaps_reference
          cp -r backstop_data/bitmaps_test ./bitmaps_test 
          git add .
          git commit -m "Deploy BackstopJS report to GitHub Pages"
          git push --force origin gh-pages

      # Post GitHub Pages Link in Comment
      - name: Post BackstopJS Report Link in Comment
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              owner: '${{ github.repository_owner }}',
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: 'BackstopJS report generated. You can view it [here](https://vamdigital.github.io/vite-storybook/html_report "Report" target="_blank").'
            })
        if: ${{ github.event_name == 'pull_request' }}

      - name: Post PR comment with report link and approval option
        if: failure() # Only post if the BackstopJS test fails
        uses: actions/github-script@v6
        with:
          script: |
            const comment_body = `
              BackstopJS visual regression test **failed**. [View the report here](https://vamdigital.github.io/vite-storybook/html_report "Report Title" target="_blank").

              If the changes are intentional, you can approve them by commenting:

              \`@bot approve visual changes\`.
            `;
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: comment_body
            });
